local luaunit = require('luaunit')

package.path = "./?.lua;./?/init.lua;" .. package.path

-- tests
require('tests.test_comparers')
require('tests.test_map')
require('tests.test_range')
require('tests.list.test_distinct')
require('tests.list.test_where')
require('tests.list.test_select')
require('tests.list.test_collect')
require('tests.list.test_any')
require('tests.list.test_first')
require('tests.list.test_last')
require('tests.list.test_max')
require('tests.list.test_min')
require('tests.list.test_sort')
require('tests.list.test_foreach')
require('tests.list.test_spread')
require('tests.list.test_fork')
require('tests.dict.test_distinct')
require('tests.dict.test_where')
require('tests.dict.test_select')
require('tests.dict.test_collect')
require('tests.dict.test_any')
require('tests.dict.test_first')
require('tests.dict.test_last')
require('tests.dict.test_max')
require('tests.dict.test_min')
require('tests.dict.test_sort')
require('tests.dict.test_foreach')
require('tests.dict.test_spread')
require('tests.dict.test_fork')

print(luaunit.LuaUnit.run())
